# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.transfer.com:
  peer0.org1.transfer.com:
  peer1.org1.transfer.com:
  peer0.org2.transfer.com:
  peer1.org2.transfer.com:

networks:
  transfer:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.transfer.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/935c0daff6b346e38fee03f72e4db36b0062eeda392a64d997b8907d57e35680_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.transfer.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/935c0daff6b346e38fee03f72e4db36b0062eeda392a64d997b8907d57e35680_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.transfer.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - transfer

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.transfer.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7448bac990da532f09829f9f9e4ba3095fe5a020e641dea95b2e07cc8ad8cf0e_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.transfer.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7448bac990da532f09829f9f9e4ba3095fe5a020e641dea95b2e07cc8ad8cf0e_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.transfer.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - transfer

  orderer.transfer.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.transfer.com
    container_name: orderer.transfer.com
    networks:
      - transfer

  peer0.org1.transfer.com:
    container_name: peer0.org1.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.transfer.com
    networks:
      - transfer

  peer1.org1.transfer.com:
    container_name: peer1.org1.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.transfer.com
    networks:
      - transfer

  peer0.org2.transfer.com:
    container_name: peer0.org2.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.transfer.com
    networks:
      - transfer

  peer1.org2.transfer.com:
    container_name: peer1.org2.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.transfer.com
    networks:
      - transfer
